if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
    set(SIMPLIFIED_CPU_ARCH_TYPE "x86_64" CACHE STRING "Autodetected cpu architecture type")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "amd64")
    set(SIMPLIFIED_CPU_ARCH_TYPE "x86_64" CACHE STRING "Autodetected cpu architecture type")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64")
    # cmake reports AMD64 on Windows, but we might be building for 32-bit.
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(SIMPLIFIED_CPU_ARCH_TYPE "x86_64" CACHE STRING "Autodetected cpu architecture type")
    else()
        set(SIMPLIFIED_CPU_ARCH_TYPE "x86" CACHE STRING "Autodetected cpu architecture type")
    endif()
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86")
    set(SIMPLIFIED_CPU_ARCH_TYPE "x86" CACHE STRING "Autodetected cpu architecture type")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "i386")
    set(SIMPLIFIED_CPU_ARCH_TYPE "x86" CACHE STRING "Autodetected cpu architecture type")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "i686")
    set(SIMPLIFIED_CPU_ARCH_TYPE "x86" CACHE STRING "Autodetected cpu architecture type")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
    set(SIMPLIFIED_CPU_ARCH_TYPE "aarch64" CACHE STRING "Autodetected cpu architecture type")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "ARM64")
    set(SIMPLIFIED_CPU_ARCH_TYPE "aarch64" CACHE STRING "Autodetected cpu architecture type")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64")
    set(SIMPLIFIED_CPU_ARCH_TYPE "aarch64" CACHE STRING "Autodetected cpu architecture type")
    # Apple A12 Bionic chipset which is added in iPhone XS/XS Max/XR uses arm64e architecture.
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64e")
    set(SIMPLIFIED_CPU_ARCH_TYPE "aarch64" CACHE STRING "Autodetected cpu architecture type")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^arm*")
    set(SIMPLIFIED_CPU_ARCH_TYPE "arm" CACHE STRING "Autodetected cpu architecture type")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "mips")
    # Just to avoid the “unknown processor” error.
    set(SIMPLIFIED_CPU_ARCH_TYPE "generic" CACHE STRING "Autodetected cpu architecture type")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "ppc64le")
    set(SIMPLIFIED_CPU_ARCH_TYPE "ppc64le" CACHE STRING "Autodetected cpu architecture type")
else()
    message(WARNING "Unknown processor:" ${CMAKE_SYSTEM_PROCESSOR})
endif()
message(STATUS "Detected architecture type: ${SIMPLIFIED_CPU_ARCH_TYPE}")
