name: MAC build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  mac-build:
    name: macos.${{ matrix.build_type }}
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [ Release , Debug ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up cache
        id: cache-cpm
        uses: actions/cache@v3
        with:
          path: ~/cpm-cache
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
      - name: Install dependencies
        run: |
          brew update
          brew upgrade openssl
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake -DCPM_SOURCE_CACHE=~/cpm-cache -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCMAKE_BUILD_TYPE=${{ matrix.compiler.build_type }} ../test
          cmake --build .
