name: Windows build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up cache
        id: cache-cpm
        uses: actions/cache@v3
        with:
          path: ~/cpm-cache
          key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
          restore-keys: ${{ runner.os }}-cpm-
      - name: Install OpenSSL
        run: choco install openssl
      - name: Install libuv
        run: choco install libuv --version 1.44.2
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake --log-level=DEBUG -DCPM_SOURCE_CACHE=~/cpm-cache ../test
          cmake --build .
