name: Windows build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build OpenSSL
        run: |
          choco install openssl
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ../test
          cmake --build .
